### ISSUE TITLE
Problem in compiling CPool packages

### ISSUE THREAD

**Issue by cydiachen** [autocyz/CornerNet_easy_use#1]
Dear CYZ， I am now using your version of CornerNet_easy_use, But now I am facing a problem when compiling Cpool. Can you help me ? I am compiling with Anaconda virtual environment, but can not get right result

**Comment by autocyz** [comment]
Is your problem similar with https://github.com/princeton-vl/CornerNet/issues/33

**Comment by cydiachen** [comment]
> Is your problem similar with [princeton-vl/CornerNet#33](https://github.com/princeton-vl/CornerNet/issues/33)

Having solved the problem, I tried to use pytorch0.4.1 and cuda9.0 environment and recompile every files which solved the problem. Also I commented several lines
